name: deploy to lambda
on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      
      - name: zip
        uses: papeloto/action-zip@v1
        with:
          files: app.py
          dest: bundle.zip
          
      - name: default deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-east-2
          function_name: lambda-push
          zip_file: bundle.zip
